update 调试

diff --git a/.github/workflows/Immortalwrt-ImageBuild-Master-x86_64.yml b/.github/workflows/Immortalwrt-ImageBuild-Master-x86_64.yml
--- a/.github/workflows/Immortalwrt-ImageBuild-Master-x86_64.yml
+++ b/.github/workflows/Immortalwrt-ImageBuild-Master-x86_64.yml
@@ -24,7 +24,6 @@ on:
 env:
   IMAGE_BUILD_URL: https://downloads.immortalwrt.org/releases/24.10.0/targets/x86/64/immortalwrt-imagebuilder-24.10.0-x86-64.Linux-x86_64.tar.zst
   SDK_URL: https://downloads.immortalwrt.org/releases/24.10.0/targets/x86/64/immortalwrt-sdk-24.10.0-x86-64_gcc-13.3.0_musl.Linux-x86_64.tar.zst
-  NIKKI_DOWNLOAD_URL: https://github.com/nikkinikki-org/OpenWrt-nikki/releases/download/v1.20.1/nikki_x86_64-openwrt-24.10.tar.gz
   IMAGE_BUILD_NAME: immortalwrt-imagebuilder-24.10.0-x86-64.Linux-x86_64.tar.zst
   LAN_IP: 192.168.51.1
   IS_SSH_DEBUG: false
@@ -110,97 +109,101 @@ jobs:
         ls -al package/ddns-go
         ls -al package/nikki
 
-    - name: Setup upterm session
-      if: env.IS_SSH_DEBUG == 'true'
-      uses: lhotari/action-upterm@v1
+    # - name: Setup upterm session
+    #   if: env.IS_SSH_DEBUG == 'true'
+    #   uses: lhotari/action-upterm@v1
 
-    - name: Build SDK Package
-      run: |
-        cd $GITHUB_WORKSPACE/sdk && ls -al
-        make package/netspeedtest/luci-app-netspeedtest/compile V=s
-        make package/ddns-go/luci-app-ddns-go/compile V=s
-        make package/nikki/luci-app-nikki/compile V=s
-        ls -al $GITHUB_WORKSPACE/sdk/bin/targets/x86/64/
-
-    # - name: Copy Nikki Package
+    # - name: Build SDK Package
     #   run: |
-    #     wget -O $GITHUB_WORKSPACE/imagebuilder/nikki.tar.gz -c $NIKKI_DOWNLOAD_URL || { echo "Nikki Download failed"; exit 1; }
-    #     mkdir -p $GITHUB_WORKSPACE/nikki
-    #     tar -xzf $GITHUB_WORKSPACE/imagebuilder/nikki.tar.gz -C $GITHUB_WORKSPACE/nikki
-    #     rm -rf $GITHUB_WORKSPACE/imagebuilder/nikki.tar.gz
-    #     ls -al $GITHUB_WORKSPACE/nikki
-    #     cp $GITHUB_WORKSPACE/nikki/*.ipk $GITHUB_WORKSPACE/imagebuilder/packages/
-    #     cd $GITHUB_WORKSPACE/imagebuilder && pwd && ls -al && cd $GITHUB_WORKSPACE/imagebuilder/packages && ls -al
+    #     cd $GITHUB_WORKSPACE/sdk && ls -al
+    #     make package/netspeedtest/luci-app-netspeedtest/compile V=s
+    #     make package/ddns-go/luci-app-ddns-go/compile V=s
+    #     make package/nikki/luci-app-nikki/compile V=s
+    #     echo '============1============='
+    #     ls -al $GITHUB_WORKSPACE/sdk/bin/packages/x86_64/packages
+    #     echo '============2============='
+    #     ls -al $GITHUB_WORKSPACE/sdk/bin/targets/x86/64/packages
+    #     echo '============END============='
 
-    - name: Download ImageBuild
-      run: |
-        wget -O $IMAGE_BUILD_NAME -c $IMAGE_BUILD_URL || { echo "Download failed"; exit 1; }
-        mkdir -p $GITHUB_WORKSPACE/imagebuilder
-        tar -I zstd -xf $IMAGE_BUILD_NAME -C $GITHUB_WORKSPACE/imagebuilder --strip-components=1
-        rm -rf $IMAGE_BUILD_NAME
+    # # - name: Copy Nikki Package
+    # #   run: |
+    # #     wget -O $GITHUB_WORKSPACE/imagebuilder/nikki.tar.gz -c $NIKKI_DOWNLOAD_URL || { echo "Nikki Download failed"; exit 1; }
+    # #     mkdir -p $GITHUB_WORKSPACE/nikki
+    # #     tar -xzf $GITHUB_WORKSPACE/imagebuilder/nikki.tar.gz -C $GITHUB_WORKSPACE/nikki
+    # #     rm -rf $GITHUB_WORKSPACE/imagebuilder/nikki.tar.gz
+    # #     ls -al $GITHUB_WORKSPACE/nikki
+    # #     cp $GITHUB_WORKSPACE/nikki/*.ipk $GITHUB_WORKSPACE/imagebuilder/packages/
+    # #     cd $GITHUB_WORKSPACE/imagebuilder && pwd && ls -al && cd $GITHUB_WORKSPACE/imagebuilder/packages && ls -al
 
-    - name: Apply config patch
-      run: |
-        cd $GITHUB_WORKSPACE/imagebuilder && ls -al
-        if [ -f .config ]; then
-          patch .config < $GITHUB_WORKSPACE/master.config.patch || { echo "Patch failed"; exit 1; }
-          echo "Patch applied successfully"
-          grep "CONFIG_ISO_IMAGES" .config
-          grep "CONFIG_TARGET_KERNEL_PARTSIZE" .config
-        else
-          echo "No .config found"
-          exit 1
-        fi
+    # - name: Download ImageBuild
+    #   run: |
+    #     wget -O $IMAGE_BUILD_NAME -c $IMAGE_BUILD_URL || { echo "Download failed"; exit 1; }
+    #     mkdir -p $GITHUB_WORKSPACE/imagebuilder
+    #     tar -I zstd -xf $IMAGE_BUILD_NAME -C $GITHUB_WORKSPACE/imagebuilder --strip-components=1
+    #     rm -rf $IMAGE_BUILD_NAME
 
-    - name: Build the firmware
-      id: compile
-      run: |
-        cp $GITHUB_WORKSPACE/sdk/bin/targets/x86/64/*.ipk $GITHUB_WORKSPACE/imagebuilder/packages/
-        PACKAGES=$(cat $GITHUB_WORKSPACE/master.packages.txt | tr '\n' ' ')
-        cd $GITHUB_WORKSPACE/imagebuilder
-        make image PROFILE="generic" PACKAGES="$PACKAGES" FILES="$GITHUB_WORKSPACE/files/master" || { echo "Compile failed"; exit 1; }
-        echo "status=success" >> $GITHUB_OUTPUT
+    # - name: Apply config patch
+    #   run: |
+    #     cd $GITHUB_WORKSPACE/imagebuilder && ls -al
+    #     if [ -f .config ]; then
+    #       patch .config < $GITHUB_WORKSPACE/master.config.patch || { echo "Patch failed"; exit 1; }
+    #       echo "Patch applied successfully"
+    #       grep "CONFIG_ISO_IMAGES" .config
+    #       grep "CONFIG_TARGET_KERNEL_PARTSIZE" .config
+    #     else
+    #       echo "No .config found"
+    #       exit 1
+    #     fi
 
-    - name: Organize files
-      id: organize
-      if: steps.compile.outputs.status == 'success' && !cancelled()
-      run: |
-        cd imagebuilder/bin/targets/x86/64/ || { echo "Directory not found"; exit 1; }
-        sha256sum *.img.gz > checksums.txt
-        echo "firmware=$PWD" >> $GITHUB_OUTPUT
-        echo "status=success" >> $GITHUB_OUTPUT
+    # - name: Build the firmware
+    #   id: compile
+    #   run: |
+    #     cp $GITHUB_WORKSPACE/sdk/bin/targets/x86/64/*.ipk $GITHUB_WORKSPACE/imagebuilder/packages/
+    #     PACKAGES=$(cat $GITHUB_WORKSPACE/master.packages.txt | tr '\n' ' ')
+    #     cd $GITHUB_WORKSPACE/imagebuilder
+    #     make image PROFILE="generic" PACKAGES="$PACKAGES" FILES="$GITHUB_WORKSPACE/files/master" || { echo "Compile failed"; exit 1; }
+    #     echo "status=success" >> $GITHUB_OUTPUT
 
-    - name: Generate release tag
-      id: tag
-      if: env.UPLOAD_RELEASE == 'true' && steps.compile.outputs.status == 'success' && !cancelled()
-      run: |
-        echo "release_tag=ImmortalWrt-Master-$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT
-        echo "ImmortalWrt Master Build" > release.txt
-        cat imagebuilder/bin/targets/x86/64/checksums.txt >> release.txt
-        echo "status=success" >> $GITHUB_OUTPUT
+    # - name: Organize files
+    #   id: organize
+    #   if: steps.compile.outputs.status == 'success' && !cancelled()
+    #   run: |
+    #     cd imagebuilder/bin/targets/x86/64/ || { echo "Directory not found"; exit 1; }
+    #     sha256sum *.img.gz > checksums.txt
+    #     echo "firmware=$PWD" >> $GITHUB_OUTPUT
+    #     echo "status=success" >> $GITHUB_OUTPUT
 
-    - name: Upload firmware to release
-      uses: softprops/action-gh-release@v2
-      if: env.UPLOAD_RELEASE == 'true' && steps.tag.outputs.status == 'success' && steps.compile.outputs.status == 'success' && !cancelled()
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      with:
-        tag_name: ${{ steps.tag.outputs.release_tag }}
-        body_path: release.txt
-        files: ${{ steps.organize.outputs.firmware }}/*
+    # - name: Generate release tag
+    #   id: tag
+    #   if: env.UPLOAD_RELEASE == 'true' && steps.compile.outputs.status == 'success' && !cancelled()
+    #   run: |
+    #     echo "release_tag=ImmortalWrt-Master-$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT
+    #     echo "ImmortalWrt Master Build" > release.txt
+    #     cat imagebuilder/bin/targets/x86/64/checksums.txt >> release.txt
+    #     echo "status=success" >> $GITHUB_OUTPUT
 
-    - name: Delete workflow runs
-      if: steps.compile.outputs.status == 'success' && !cancelled()
-      uses: Mattraks/delete-workflow-runs@v2
-      with:
-        retain_days: 1
-        keep_minimum_runs: 3
+    # - name: Upload firmware to release
+    #   uses: softprops/action-gh-release@v2
+    #   if: env.UPLOAD_RELEASE == 'true' && steps.tag.outputs.status == 'success' && steps.compile.outputs.status == 'success' && !cancelled()
+    #   env:
+    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    #   with:
+    #     tag_name: ${{ steps.tag.outputs.release_tag }}
+    #     body_path: release.txt
+    #     files: ${{ steps.organize.outputs.firmware }}/*
 
-    - name: Delete Older Releases
-      uses: dev-drprasad/delete-older-releases@v0.3.4
-      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
-      with:
-        keep_latest: 5
-        delete_tags: true
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    # - name: Delete workflow runs
+    #   if: steps.compile.outputs.status == 'success' && !cancelled()
+    #   uses: Mattraks/delete-workflow-runs@v2
+    #   with:
+    #     retain_days: 1
+    #     keep_minimum_runs: 3
+
+    # - name: Delete Older Releases
+    #   uses: dev-drprasad/delete-older-releases@v0.3.4
+    #   if: env.UPLOAD_RELEASE == 'true' && !cancelled()
+    #   with:
+    #     keep_latest: 5
+    #     delete_tags: true
+    #   env:
+    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
