update

diff --git a/.github/workflows/Immortalwrt-ImageBuild-Master-x86_64.yml b/.github/workflows/Immortalwrt-ImageBuild-Master-x86_64.yml
--- a/.github/workflows/Immortalwrt-ImageBuild-Master-x86_64.yml
+++ b/.github/workflows/Immortalwrt-ImageBuild-Master-x86_64.yml
@@ -23,6 +23,7 @@ on:
 
 env:
   IMAGE_BUILD_URL: https://downloads.immortalwrt.org/releases/24.10.0/targets/x86/64/immortalwrt-imagebuilder-24.10.0-x86-64.Linux-x86_64.tar.zst
+  NIKKI_DOWNLOAD_URL: https://github.com/nikkinikki-org/OpenWrt-nikki/releases/download/v1.20.1/nikki_x86_64-openwrt-24.10.tar.gz
   IMAGE_BUILD_NAME: immortalwrt-imagebuilder-24.10.0-x86-64.Linux-x86_64.tar.zst
   UPLOAD_RELEASE: true
   DELETE_USELESS_FILES: true
@@ -95,7 +96,16 @@ jobs:
         mkdir -p $GITHUB_WORKSPACE/imagebuilder
         tar -I zstd -xf $IMAGE_BUILD_NAME -C $GITHUB_WORKSPACE/imagebuilder --strip-components=1
         rm -rf $IMAGE_BUILD_NAME
-        cd $GITHUB_WORKSPACE/imagebuilder && pwd && ls -al
+
+    - name: Copy Nikki Package
+      run: |
+        wget -O $GITHUB_WORKSPACE/imagebuilder/nikki.tar.gz -c $NIKKI_DOWNLOAD_URL || { echo "Nikki Download failed"; exit 1; }
+        mkdir -p $GITHUB_WORKSPACE/nikki
+        tar -xz $GITHUB_WORKSPACE/imagebuilder/nikki.tar.gz -C $GITHUB_WORKSPACE/nikki
+        rm -rf $GITHUB_WORKSPACE/imagebuilder/nikki.tar.gz
+        ls -al $GITHUB_WORKSPACE/nikki
+        cp $GITHUB_WORKSPACE/nikki/*.ipk $GITHUB_WORKSPACE/imagebuilder/packages/
+        cd $GITHUB_WORKSPACE/imagebuilder && pwd && ls -al && cd $GITHUB_WORKSPACE/imagebuilder/packages && ls -al
 
     - name: Apply config patch
       run: |
